#!/usr/bin/env php
<?php

use ICanBoogie\CLDR\CLI\App;

if (version_compare('8.1.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of CLDR requires PHP >= 8.1.' . PHP_EOL .
            'You are using PHP %s (%s).' . PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );

    die(1);
}

if (isset($GLOBALS['_composer_autoload_path'])) {
    define('CLDR_COMPOSER_INSTALL', $GLOBALS['_composer_autoload_path']);

    unset($GLOBALS['_composer_autoload_path']);
} else {
    foreach (
        [
            __DIR__ . '/../../autoload.php',
            __DIR__ . '/../vendor/autoload.php',
            __DIR__ . '/vendor/autoload.php'
        ] as $file
    ) {
        if (file_exists($file)) {
            define('CLDR_COMPOSER_INSTALL', $file);

            break;
        }
    }

    unset($file);
}

if (!defined('CLDR_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require CLDR_COMPOSER_INSTALL;

App::run();
